### ISSUE TITLE
Facing issue after SIM post

### ISSUE THREAD

**Issue by Se7venDevelopers** [SammyK/codeigniter-authorize.net-aim-api#1]
Hi Sammy K, I really appreciate for your AIM code [Codeingniter].
But i am integrating DPM Method of authorize .net in my website so. do you help me with that.
I want to post data of user on Authorize .net website where they can purchase using credit card.

I am very thank full for that. [Reply me.]

**Comment by SammyK** [comment]
Hey @Se7venDevelopers! Sorry but this repo is no longer being maintained.

> Warning: This repo is no longer being maintained. Use at your own risk.

Good luck! :)
